// src/app/layout.js
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import { ChakraProvider } from '@chakra-ui/react';
export default function RootLayout({ children }) {
  return (
    <ChakraProvider>
      {children} 
    </ChakraProvider>
  );
}
